routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('synonyms','SynonymsController');

app/Synonyms.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Synonyms extends Model
{
    protected $fillable = ['key','tags'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Synonyms;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Synonyms=Synonyms::whereNotNull('tags')->get();

        $SynonymsNUll=Synonyms::whereNull('tags')->get();

        return view('home')->with(compact('Synonyms','SynonymsNUll'));
    }
}

app/Http/Controllers/SynonymsController.php
<?php

namespace App\Http\Controllers;

use App\Synonyms;
use Illuminate\Http\Request;

class SynonymsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'key' => 'required',
            'tags' => 'required',
        ]);

        Synonyms::create($request->all());

        return redirect()->route('home')->with('success','Synonyms added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Synonyms  $synonyms
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        
        $Synonyms = Synonyms::find($id);

        // dd($voucher->bill);
        if(empty($Synonyms)){
            abort(404);
        }
        return view('show')->with('synonyms',$Synonyms);
    //     $id = request()->segment(count(request()->segments()));
    //     $Synonyms=Synonyms::Where('id','=',unserialize($id) );
        
    //     return view('show')->with('synonyms',$Synonyms);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Synonyms  $synonyms
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Synonyms = Synonyms::find($id);
        return view('edit')->with(compact('Synonyms'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Synonyms  $synonyms
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request)
    {
        $Synonyms = Synonyms::find($id);
        $key = $request->key;
        $tags = $request->tags;
        $Synonyms->key = $key;
        $Synonyms->tags = $tags;
    

        if( $Synonyms->save() === true ){
            return redirect('home')->with('success', 'Information has been added');
        }
        else{
            return redirect('home')->with('error', 'could not add');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Synonyms  $synonyms
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $synonyms = Synonyms::find($id);
        $synonyms->delete();
        return redirect('home')->with('success','Information has been  deleted');
    }
}

resources/views/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

                <form action="{{ route('synonyms.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="key">Key</label>
                        <input type="text" class="form-control" name="key" id="key" aria-describedby="keyHelp" placeholder="Enter key name">
                        <small id="keyHelp" class="form-text text-muted">key name of the tags in next field.</small>
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <textarea type="text" class="form-control" name="tags" id="tags" placeholder="Tags"></textarea>
                        <small id="keyHelp" class="form-text text-muted">tags relating to the key name</small>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

        </div>
    </div>
</div> 
@endsection

resources/views/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Edit</h2><br  />
      <form method="post" action="{{action('SynonymsController@update',$Synonyms->id )}}">
      @csrf
      <input name="_method" type="hidden" value="PATCH">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="form-group col-md-4">
          <label for="ref">KEY:</label>
          <input type="text" class="form-control" name="key" id="key" value="{{$Synonyms->key}}">
        </div>
      </div>
      <div class="row">
        <div class="col-md-4"></div>
          <div class="form-group col-md-4">
            <label for="amount">TAGS:</label>
            <input type="text" class="form-control" name="tags" id="tags" value="{{$Synonyms->tags}}">
          </div>
        </div> 
       

      <div class="row">
        <div class="col-md-4"></div>
        <div class="form-group col-md-4" style="margin-top:60px">
          <button type="submit" class="btn btn-success" style="margin-left:38px">Update</button>
        </div>
      </div>
    </form>
  </div>

  @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
                @if (Session::has('success'))
                <div class="alert alert-success">
                  {{ Session::get('success') }}
                </div><br />
               @endif
                <a class="btn btn-outline-success btn-sm btnview" role="button" href="{{ url('synonyms/create') }}">NEW</a>
                <br>
                <br>
                <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Key</th>
                            <th scope="col">Tags</th>
                            <th></th>
                            <th></th>
                          </tr> 
                        </thead> 
                        <tbody>
                            @foreach ($Synonyms as $Synonym)
                                <tr>
                                    <th scope="row"></th>
                                    <td>{{$Synonym->key}}</td>
                                    <td>{{$Synonym->tags}}</td>
                                    <td><a class="btn btn-outline-success btn-sm btnview" role="button" href="{{ url('synonyms/'. $Synonym->id.'/edit') }}">EDIT</a></td>
                                    <td>
                                        <form action="{{action('SynonymsController@destroy', $Synonym->id)}}" method="post">
                                          @csrf
                                          <input name="_method" type="hidden" value="DELETE">
                                          <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>

                      <hr>
                      <h3>Pendding</h3>
                      <hr>

                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Key</th>
                            <th scope="col">Tags</th>
                            <th></th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($SynonymsNUll as $Synonym)
                                <tr>
                                    <th scope="row"></th>
                                    <td>{{$Synonym->key}}</td>
                                    <td>{{$Synonym->tags}}</td>
                                    <td><a class="btn btn-outline-success btn-sm btnview" role="button" href="{{ url('synonyms/'. $Synonym->id.'/edit') }}">EDIT</a></td>
                                    <td>
                                        <form action="{{action('SynonymsController@destroy', $Synonym->id)}}" method="post">
                                          @csrf
                                          <input name="_method" type="hidden" value="DELETE">
                                          <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>


        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'MyADK') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/show.blade.php
@extends('layouts.app')

@section('content')
<table class="table">

    <h1>{{$synonyms->key}}</h1>
    <p>{{$synonyms->tags}}</p>
    


<a href="synonyms/{{$synonyms->id}}/edit">EDIT</a>

@endsection